name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 5.1.2
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.19.0
  template_string: 
    path: ../template_string
