name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^1.2.2
  meta: ^1.3.0
  csv: ^6.0.0
  recase: ^4.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0 
  source_gen: ^1.0.0
  flutter_sheet_localization:
    path: ../flutter_sheet_localization
  build: ^2.0.0
  analyzer: ^6.7.0
  collection: ^1.18.0
  intl: ^0.19.0
  localization_builder:
    path: ../localization_builder

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^2.4.12
